/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.farmacia.laboratorio9;

/**
 *
 * @author HP
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPaneAbogadosContainer = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldAbJuniorNombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldAbJuniorApellidos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldAbJuniorNumHijos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldAbJuniorAniosExperiencia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldAbJuniorNumCasosCargo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAbogadoJunior = new javax.swing.JTextArea();
        jButtonAbJunior = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldAbJuniorNumCasosApoyo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldAbSeniorNombres = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldAbSeniorApellidos = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldAbSeniorNumHijos = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldAbSeniorAniosExperiencia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldAbSeniorNumCasosCargo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaAbogadoSenior = new javax.swing.JTextArea();
        jButtonAbSenior = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldAbSocioNombres = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldAbSocioApellidos = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldAbSocioNumHijos = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldAbSocioExperiencia = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldAbSocioNumCasosCargo = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaAbogadoSocio = new javax.swing.JTextArea();
        jButtonAbSocio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setText("Nombres");

        jTextFieldAbJuniorNombres.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 2, 8));
        jTextFieldAbJuniorNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAbJuniorNombresActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setText("Apellidos");

        jTextFieldAbJuniorApellidos.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 2, 8));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setText("Numero de hijos");

        jTextFieldAbJuniorNumHijos.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 2, 8));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setText("Anos de experiencia");

        jTextFieldAbJuniorAniosExperiencia.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 2, 8));
        jTextFieldAbJuniorAniosExperiencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAbJuniorAniosExperienciaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setText("Numero de casos a cargo");

        jTextFieldAbJuniorNumCasosCargo.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 2, 8));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));

        jTextAreaAbogadoJunior.setColumns(20);
        jTextAreaAbogadoJunior.setLineWrap(true);
        jTextAreaAbogadoJunior.setRows(5);
        jTextAreaAbogadoJunior.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        jScrollPane1.setViewportView(jTextAreaAbogadoJunior);

        jButtonAbJunior.setBackground(java.awt.Color.red);
        jButtonAbJunior.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jButtonAbJunior.setForeground(java.awt.Color.white);
        jButtonAbJunior.setText("MOSTRAR");
        jButtonAbJunior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbJuniorActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setText("Numero de casos apoyo");

        jTextFieldAbJuniorNumCasosApoyo.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 2, 8));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAbJunior, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldAbJuniorNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldAbJuniorApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldAbJuniorNumHijos, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldAbJuniorAniosExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldAbJuniorNumCasosCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldAbJuniorNumCasosApoyo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldAbJuniorNumHijos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldAbJuniorApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldAbJuniorNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldAbJuniorAniosExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldAbJuniorNumCasosCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldAbJuniorNumCasosApoyo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButtonAbJunior, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPaneAbogadosContainer.addTab("Abogado Junior", jPanel2);

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setText("Nombres");

        jTextFieldAbSeniorNombres.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 2, 8));
        jTextFieldAbSeniorNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAbSeniorNombresActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel9.setText("Apellidos");

        jTextFieldAbSeniorApellidos.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 2, 8));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel10.setText("Numero de hijos");

        jTextFieldAbSeniorNumHijos.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 2, 8));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel11.setText("Anos de experiencia");

        jTextFieldAbSeniorAniosExperiencia.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 2, 8));
        jTextFieldAbSeniorAniosExperiencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAbSeniorAniosExperienciaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel12.setText("Numero de casos a cargo");

        jTextFieldAbSeniorNumCasosCargo.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 2, 8));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));

        jTextAreaAbogadoSenior.setColumns(20);
        jTextAreaAbogadoSenior.setLineWrap(true);
        jTextAreaAbogadoSenior.setRows(5);
        jTextAreaAbogadoSenior.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        jScrollPane2.setViewportView(jTextAreaAbogadoSenior);

        jButtonAbSenior.setBackground(java.awt.Color.red);
        jButtonAbSenior.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jButtonAbSenior.setText("MOSTRAR");
        jButtonAbSenior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbSeniorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAbSenior, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldAbSeniorNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldAbSeniorApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldAbSeniorNumHijos, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10)))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldAbSeniorAniosExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldAbSeniorNumCasosCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12))))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(jScrollPane2))
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldAbSeniorNumHijos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldAbSeniorApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldAbSeniorNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldAbSeniorAniosExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldAbSeniorNumCasosCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(26, 26, 26)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                    .addComponent(jButtonAbSenior, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(21, 21, 21)))
        );

        jTabbedPaneAbogadosContainer.addTab("Abogado Senior", jPanel3);

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel13.setText("Nombres");

        jTextFieldAbSocioNombres.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 2, 8));
        jTextFieldAbSocioNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAbSocioNombresActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel14.setText("Apellidos");

        jTextFieldAbSocioApellidos.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 2, 8));

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel15.setText("Numero de hijos");

        jTextFieldAbSocioNumHijos.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 2, 8));

        jLabel16.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel16.setText("Anos de experiencia");

        jTextFieldAbSocioExperiencia.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 2, 8));
        jTextFieldAbSocioExperiencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAbSocioExperienciaActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel17.setText("Numero de casos a cargo");

        jTextFieldAbSocioNumCasosCargo.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 2, 8));

        jScrollPane3.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));

        jTextAreaAbogadoSocio.setColumns(20);
        jTextAreaAbogadoSocio.setLineWrap(true);
        jTextAreaAbogadoSocio.setRows(5);
        jTextAreaAbogadoSocio.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        jScrollPane3.setViewportView(jTextAreaAbogadoSocio);

        jButtonAbSocio.setBackground(java.awt.Color.red);
        jButtonAbSocio.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jButtonAbSocio.setText("MOSTRAR");
        jButtonAbSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbSocioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAbSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldAbSocioNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldAbSocioApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldAbSocioNumHijos, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15)))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldAbSocioExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel16))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldAbSocioNumCasosCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel17))))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(jScrollPane3))
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldAbSocioNumHijos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldAbSocioApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldAbSocioNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldAbSocioExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldAbSocioNumCasosCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(26, 26, 26)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                    .addComponent(jButtonAbSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(21, 21, 21)))
        );

        jTabbedPaneAbogadosContainer.addTab("Abogado Socio", jPanel4);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setText("REGISTRO DE ABOGADOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jTabbedPaneAbogadosContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPaneAbogadosContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAbJuniorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbJuniorActionPerformed
        // TODO add your handling code here:

        String nombres = jTextFieldAbJuniorNombres.getText();
        String apellidos = jTextFieldAbJuniorApellidos.getText();
        String status = "Junior";
        String numHijosString = jTextFieldAbJuniorNumHijos.getText();
        int numHijos = Integer.parseInt(numHijosString);
        String aniosExperienciaString = jTextFieldAbJuniorAniosExperiencia.getText();
        int aniosExperiencia = Integer.parseInt(aniosExperienciaString);
        String numCasosCargoString = jTextFieldAbJuniorNumCasosCargo.getText();
        int numCasosCargo = Integer.parseInt(numCasosCargoString);
        String numCasosApoyoString = jTextFieldAbJuniorNumCasosApoyo.getText();
        int numCasosApoyo = Integer.parseInt(numCasosApoyoString);
        // Por hacer: validacion de datos

        AbogadoJunior abogadoJunior = new AbogadoJunior(nombres, apellidos, status, numHijos, aniosExperiencia, numCasosCargo, numCasosApoyo);
        String abogadoJuniorInfo = abogadoJunior.getInfo();
        jTextAreaAbogadoJunior.setText(abogadoJuniorInfo);
    }//GEN-LAST:event_jButtonAbJuniorActionPerformed

    private void jTextFieldAbJuniorNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAbJuniorNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAbJuniorNombresActionPerformed

    private void jTextFieldAbJuniorAniosExperienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAbJuniorAniosExperienciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAbJuniorAniosExperienciaActionPerformed

    private void jTextFieldAbSeniorNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAbSeniorNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAbSeniorNombresActionPerformed

    private void jTextFieldAbSeniorAniosExperienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAbSeniorAniosExperienciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAbSeniorAniosExperienciaActionPerformed

    private void jButtonAbSeniorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbSeniorActionPerformed
        String nombres = jTextFieldAbSeniorNombres.getText();
        String apellidos = jTextFieldAbSeniorApellidos.getText();
        String status = "Senior";
        String numHijosString = jTextFieldAbSeniorNumHijos.getText();
        int numHijos = Integer.parseInt(numHijosString);
        String aniosExperienciaString = jTextFieldAbSeniorAniosExperiencia.getText();
        int aniosExperiencia = Integer.parseInt(aniosExperienciaString);
        String numCasosCargoString = jTextFieldAbSeniorNumCasosCargo.getText();
        int numCasosCargo = Integer.parseInt(numCasosCargoString);

        AbogadoSenior abogadoSenior = new AbogadoSenior(nombres, apellidos, status, numHijos, aniosExperiencia, numCasosCargo);
        String abogadoSeniorInfo = abogadoSenior.getInfo();
        jTextAreaAbogadoSenior.setText(abogadoSeniorInfo);        
    }//GEN-LAST:event_jButtonAbSeniorActionPerformed

    private void jTextFieldAbSocioNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAbSocioNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAbSocioNombresActionPerformed

    private void jTextFieldAbSocioExperienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAbSocioExperienciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAbSocioExperienciaActionPerformed

    private void jButtonAbSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbSocioActionPerformed
        String nombres = jTextFieldAbSocioNombres.getText();
        String apellidos = jTextFieldAbSocioApellidos.getText();
        String status = "Senior";
        String numHijosString = jTextFieldAbSocioNumHijos.getText();
        int numHijos = Integer.parseInt(numHijosString);
        String aniosExperienciaString = jTextFieldAbSocioExperiencia.getText();
        int aniosExperiencia = Integer.parseInt(aniosExperienciaString);
        String numCasosCargoString = jTextFieldAbSocioNumCasosCargo.getText();
        int numCasosCargo = Integer.parseInt(numCasosCargoString);

        AbogadoSocio abogadoSocio = new AbogadoSocio(nombres, apellidos, status, numHijos, aniosExperiencia, numCasosCargo);
        String abogadoSocioInfo = abogadoSocio.getInfo();
        jTextAreaAbogadoSocio.setText(abogadoSocioInfo);           
    }//GEN-LAST:event_jButtonAbSocioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbJunior;
    private javax.swing.JButton jButtonAbSenior;
    private javax.swing.JButton jButtonAbSocio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPaneAbogadosContainer;
    private javax.swing.JTextArea jTextAreaAbogadoJunior;
    private javax.swing.JTextArea jTextAreaAbogadoSenior;
    private javax.swing.JTextArea jTextAreaAbogadoSocio;
    private javax.swing.JTextField jTextFieldAbJuniorAniosExperiencia;
    private javax.swing.JTextField jTextFieldAbJuniorApellidos;
    private javax.swing.JTextField jTextFieldAbJuniorNombres;
    private javax.swing.JTextField jTextFieldAbJuniorNumCasosApoyo;
    private javax.swing.JTextField jTextFieldAbJuniorNumCasosCargo;
    private javax.swing.JTextField jTextFieldAbJuniorNumHijos;
    private javax.swing.JTextField jTextFieldAbSeniorAniosExperiencia;
    private javax.swing.JTextField jTextFieldAbSeniorApellidos;
    private javax.swing.JTextField jTextFieldAbSeniorNombres;
    private javax.swing.JTextField jTextFieldAbSeniorNumCasosCargo;
    private javax.swing.JTextField jTextFieldAbSeniorNumHijos;
    private javax.swing.JTextField jTextFieldAbSocioApellidos;
    private javax.swing.JTextField jTextFieldAbSocioExperiencia;
    private javax.swing.JTextField jTextFieldAbSocioNombres;
    private javax.swing.JTextField jTextFieldAbSocioNumCasosCargo;
    private javax.swing.JTextField jTextFieldAbSocioNumHijos;
    // End of variables declaration//GEN-END:variables
}
